import { Link } from "wouter";
import { useGetPrescription, getGetPrescriptionQueryKey } from "@workspace/api-client-react";
import { ArrowLeft, Printer } from "lucide-react";

export default function PrescriptionDetailPage({ id }: { id: number }) {
  const { data: rx, isLoading } = useGetPrescription(id, {
    query: { queryKey: getGetPrescriptionQueryKey(id) }
  });

  if (isLoading) return <div className="p-8 text-center text-muted-foreground">Loading...</div>;
  if (!rx) return <div className="p-8 text-center text-muted-foreground">Prescription not found</div>;

  return (
    <div className="p-6 max-w-3xl mx-auto space-y-6">
      <div className="flex items-center gap-3 print:hidden">
        <Link href="/prescriptions" className="p-2 rounded-lg hover:bg-muted text-muted-foreground">
          <ArrowLeft size={18}/>
        </Link>
        <h1 className="text-2xl font-bold flex-1">Prescription #{rx.id}</h1>
        <button onClick={() => window.print()} className="flex items-center gap-2 px-4 py-2 rounded-lg border border-border text-sm hover:bg-muted">
          <Printer size={15} /> Print
        </button>
      </div>

      <div className="bg-card border border-card-border rounded-xl p-6 print:border-2 print:p-8">
        <div className="text-center mb-6 pb-4 border-b border-border">
          <h2 className="text-xl font-bold text-foreground">ClinicDesk Medical Center</h2>
          <p className="text-muted-foreground text-sm">Prescription</p>
        </div>

        <div className="grid grid-cols-2 gap-4 mb-6 text-sm">
          <div>
            <p className="text-muted-foreground">Patient</p>
            <p className="font-semibold text-foreground">{rx.patientName ?? `Patient #${rx.patientId}`}</p>
          </div>
          <div>
            <p className="text-muted-foreground">Prescribing Doctor</p>
            <p className="font-semibold text-foreground">Dr. {rx.doctorName ?? rx.doctorId}</p>
          </div>
          <div>
            <p className="text-muted-foreground">Issue Date</p>
            <p className="font-medium text-foreground">{rx.issuedAt}</p>
          </div>
          {rx.visitId && (
            <div>
              <p className="text-muted-foreground">Visit Reference</p>
              <p className="font-medium text-foreground">Visit #{rx.visitId}</p>
            </div>
          )}
        </div>

        <div className="space-y-3 mb-6">
          <h3 className="font-semibold text-foreground border-b border-border pb-2">Medications</h3>
          {rx.medications.map((m, i) => (
            <div key={i} className="p-4 border border-border rounded-lg">
              <p className="font-semibold text-foreground">{i + 1}. {m.name}</p>
              <p className="text-sm text-muted-foreground mt-1">
                <span className="font-medium">{m.dosage}</span> · {m.frequency} · {m.duration}
              </p>
              {m.instructions && <p className="text-sm text-muted-foreground mt-0.5 italic">{m.instructions}</p>}
            </div>
          ))}
        </div>

        {rx.notes && (
          <div className="p-4 bg-muted/30 rounded-lg">
            <p className="text-sm font-medium text-muted-foreground mb-1">Additional Notes</p>
            <p className="text-sm text-foreground">{rx.notes}</p>
          </div>
        )}

        <div className="mt-8 pt-4 border-t border-border flex justify-between text-xs text-muted-foreground">
          <span>Generated by ClinicDesk</span>
          <span>Date: {new Date().toLocaleDateString()}</span>
        </div>
      </div>
    </div>
  );
}
